apiVersion: v1
kind: Service
metadata:
  labels:
    app: cosmosdata
  name: cosmosdata-svc
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    name: http
  selector:
    app: cosmosdata
  type: LoadBalancer